### ISSUE TITLE
Error in utils

### ISSUE THREAD

**Issue by KleinhansDa** [exasol/r-exasol#48] opened 2020-07-31 16:12 UTC
Hi,

when I want to install from github R gives me this error message

`devtools::install_github("EXASOL/r-exasol")
Downloading GitHub repo EXASOL/r-exasol@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/EXASOL/r-exasol/tarball/HEAD'`

Session Info:

`R version 3.5.1 (--) 
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS
Matrix products: default
BLAS/LAPACK: /usr/lib/libopenblasp-r0.2.18.so`
`locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C`
`attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base`
`other attached packages:
[1] Rook_1.1-1      RJSONIO_1.3-1.2 Cairo_1.5-6`
`loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1        magrittr_1.5      usethis_1.6.1     devtools_2.3.1   
 [5] pkgload_1.0.2     R6_2.4.0          brew_1.0-6        rlang_0.4.7      
 [9] fansi_0.4.0       tools_3.5.1       pkgbuild_1.1.0    sessioninfo_1.1.1
[13] cli_2.0.2         withr_2.1.2       ellipsis_0.3.1    remotes_2.2.0    
[17] assertthat_0.2.1  digest_0.6.19     rprojroot_1.3-2   crayon_1.3.4     
[21] processx_3.4.3    callr_3.4.3       fs_1.3.1          ps_1.3.0         
[25] codetools_0.2-16  curl_3.3          testthat_2.3.2    memoise_1.1.0    
[29] glue_1.4.1        compiler_3.5.1    desc_1.2.0        backports_1.1.4  
[33] prettyunits_1.0.2`

Any idea?

Best,

David

**Comment by tkilias** [comment] 2020-08-03 10:27
Hi @KleinhansDa,

This looks like it was a temporary issue. I tried to access the link the installation could not access in your error message. I was able access it, because of that, I think it was a network issue or a Github API issue. Please try the installation again. If it still doesn't work we need to see, if I can reproduce it. 

Best,
tkilias

**Comment by tkilias** [comment] 2020-08-10 15:47
Hi @KleinhansDa,

any news on this issue? Or, can I close it?

Best,
tkilias

**Comment by KleinhansDa** [comment] 2020-08-10 17:32
Hi @tkilias. Sorry for the delay. 

I solved the issue by copying the libraries from another project. Unfortunately I can not confirm your suggestion. I will try next time!

You may close the issue.

Thanks!

**Comment by tkilias** [comment] 2020-08-12 03:26
Hi @KleinhansDa,

Thanks, for the response. I am closing the ticket now.

Best,
tkilias

**Closed by tkilias** 2020-08-12 03:26 UTC
